<?php 
    $autoUsate = [
        [
            'id' => 1,
            'marca' => 'Fiat',
            'modello' => 'Panda',
            'immatricolazione' => 1995,
            'proprietari_precedenti' => 3,
            'allestimento' => '',
            'cavalli' => 69,
            'alimentazione' => 'Metano',
            'cilindrata' => 1200,
            'cambio' => 'manuale',
            'posti_a_sedere' => 4,
            'aria_condizionata' => false,
            'prezzo' => 1200,
            'kilometraggio' => 180000,
        ],
        [
            'id' => 2,
            'marca' => 'Ford',
            'modello' => 'Fiesta',
            'immatricolazione' => 2002,
            'proprietari_precedenti' => 1,
            'allestimento' => '',
            'cavalli' => 68,
            'alimentazione' => 'Diesel',
            'cilindrata' => 1400,
            'cambio' => 'manuale',
            'posti_a_sedere' => 5,
            'aria_condizionata' => true,
            'prezzo' => 2400,
            'kilometraggio' => 168000,
        ],
        [
            'id' => 3,
            'marca' => 'Audi',
            'modello' => 'A4',
            'immatricolazione' => 2008,
            'proprietari_precedenti' => 2,
            'allestimento' => '',
            'cavalli' => 140,
            'alimentazione' => 'Diesel',
            'cilindrata' => 1900,
            'cambio' => 'automatico',
            'posti_a_sedere' => 5,
            'aria_condizionata' => true,
            'prezzo' => 5000,
            'kilometraggio' => 210000,
        ],
        [
            'id' => 4,
            'marca' => 'Seat',
            'modello' => 'Ibiza',
            'immatricolazione' => 2015,
            'proprietari_precedenti' => 1,
            'allestimento' => '',
            'cavalli' => 90,
            'alimentazione' => 'Benzina',
            'cilindrata' => 1600,
            'cambio' => 'manuale',
            'posti_a_sedere' => 5,
            'aria_condizionata' => true,
            'prezzo' => 8000,
            'kilometraggio' => 148000,
        ],
        [
            'id' => 5,
            'marca' => 'BMW',
            'modello' => 'Z3',
            'immatricolazione' => 2012,
            'proprietari_precedenti' => 3,
            'allestimento' => '',
            'cavalli' => 220,
            'alimentazione' => 'Benzina',
            'cilindrata' => 3000,
            'cambio' => 'manuale',
            'posti_a_sedere' => 2,
            'aria_condizionata' => true,
            'prezzo' => 12000,
            'kilometraggio' => 140000,
        ],
    ];
?>